# from game import Game
# from player import Player
import socket
import sys
import eventlet
import socketio
import random
import string

from queue import Queue

class Host:
    def __init__(self, code, message_queue: Queue):
        self.sio = socketio.Server(cors_allowed_origins="*")
        self.app = socketio.WSGIApp(self.sio)
        self.players = {}
        self.gameCode = code
        self.server = None
        self.message_queue = message_queue
        
        # init events
        self.sio.event(self.connect)
        self.sio.event(self.disconnect)
        self.sio.on("gameCode", self.checkCode)
        self.sio.on("userName", self.newUser)

    def get_code_message(self):
        '''get code message generated by game'''
        message = self.message_queue.get()
        return message
        
    def run(self):
        '''start the server'''
        self.server = eventlet.listen(('0.0.0.0', 5100))
        eventlet.wsgi.server(self.server, self.app, log_output=False)

    def printServerInfo(self):
        print(f"\nBox code: {self.gameCode}\n")
        print(f"Players: {list(self.players.values())}")

    def connect(self, sid, environ):
        print(f"New client {sid} connected.")
        self.players[sid] = f"Player {len(self.players) + 1}"
        self.printServerInfo()

    def disconnect(self, sid):
        print(f"Client {sid} ({self.players[sid]}) disconnected.")
        del self.players[sid]
        self.printServerInfo()

    def checkCode(self, sid, data):
        print(f"Received game code {data} from connected client {sid}.")
        if(data == self.gameCode):
            self.sio.emit("codeAccepted", room=sid)
            print(f"Client {sid} code accepted.")
            self.printServerInfo()
        else:
            self.sio.emit("codeDenied", room=sid)
            print(f"Client {sid} code denied.")
        
    def newUser(self, sid, data):
        print(f"Client {sid} player name set to {data}.")
        self.players[sid] = data
        self.printServerInfo()
    
    def stop(self):
        '''safely stop the server'''
        if self.server:
            self.server.close()

# if __name__ == '__main__':
#     host = Host()
#     host.run()

# MAX_CONNECTIONS = 20
